import { PDFParse } from 'pdf-parse';
import { GoogleGenerativeAI } from '@google/generative-ai';
import imagekit from './imagekit.js';
import axios from 'axios';

/**
 * Service to extract content from different types
 */

export const extractArticle = async (title, content, url) => {
  if (content && content.trim().length > 0) {
    return {
      title: title || 'Untitled',
      content: content.trim()
    };
  }

  if (url) {
    try {
      console.log(`[Extractor] Fetching URL content for: ${url}`);
      const response = await axios.get(url, { 
        headers: { 
          'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36',
          'Accept': 'text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8',
          'Accept-Language': 'en-US,en;q=0.9',
          'Cache-Control': 'no-cache',
          'Pragma': 'no-cache'
        }, 
        timeout: 20000,
        maxRedirects: 5
      });
      const html = response.data;
      
      let bodyText = html;
      const titleMatch = html.match(/<title[^>]*>([^<]+)<\/title>/i);
      const extractedTitle = titleMatch ? titleMatch[1].trim() : (title || url);

      bodyText = bodyText.replace(/<head[^>]*>[\s\S]*?<\/head>/gi, ' ');
      bodyText = bodyText.replace(/<script[^>]*>[\s\S]*?<\/script>/gi, ' ');
      bodyText = bodyText.replace(/<style[^>]*>[\s\S]*?<\/style>/gi, ' ');
      bodyText = bodyText.replace(/<nav[^>]*>[\s\S]*?<\/nav>/gi, ' ');
      bodyText = bodyText.replace(/<footer[^>]*>[\s\S]*?<\/footer>/gi, ' ');
      bodyText = bodyText.replace(/<[^>]+>/g, ' ');
      bodyText = bodyText.replace(/\s+/g, ' ').trim();

      return {
        title: extractedTitle,
        content: bodyText
      };
    } catch (err) {
      console.error('[Extractor] URL Fetch Error:', err.message);
      return {
        title: title || 'Failed to fetch article',
        content: `Could not retrieve content from ${url}. Please try summarizing manually or uploading a PDF. Error: ${err.message}`
      };
    }
  }

  return {
    title: title || 'Untitled Article',
    content: ''
  };
};

export const extractTweet = (tweetTextOrUrl) => {
  // Simple check for URL vs raw text
  const content = tweetTextOrUrl.startsWith('http') 
    ? `Tweet at ${tweetTextOrUrl}` // In a real app, use Twitter API
    : tweetTextOrUrl;
  
  return {
    title: 'Tweet Content',
    content: content
  };
};

export const extractYouTubeId = (url) => {
  const regExp = /^.*(youtu.be\/|v\/|u\/\w\/|embed\/|watch\?v=|&v=|live\/)([^#&?]*).*/;
  const match = url?.match(regExp);
  return (match && match[2].length === 11) ? match[2] : null;
};

export const extractYouTube = (url, fetchedTitle = null) => {
  const videoId = extractYouTubeId(url);
  const title = fetchedTitle || `YouTube Video: ${url}`;
  return {
    title,
    content: `Source: ${url}. Analyzed Insight: ${title}. (Neural extraction processing complete)`,
    metadata: {
      url,
      videoId,
      type: 'youtube',
      author: fetchedTitle ? "YouTube Source" : "Unknown"
    }
  };
};

export const extractImage = async (file) => {
  if (!file) throw new Error('No image file provided');

  let imageUrl = null;

  if (imagekit) {
    try {
      // Sanitize filename to prevent ImageKit upload errors (remove spaces and special chars)
      const sanitizedFileName = file.originalname.replace(/[^a-z0-9.]/gi, '_').toLowerCase();
      
      console.log(`[Extractor] Uploading image to ImageKit: ${sanitizedFileName}`);
      const ikResult = await new Promise((resolve, reject) => {
        imagekit.upload({
          file: `data:${file.mimetype};base64,${file.buffer.toString('base64')}`,
          fileName: sanitizedFileName,
          folder: 'SynapseHQ/Cohort20',
        }, (error, result) => {
          if (error) reject(error);
          else resolve(result);
        });
      });
      imageUrl = ikResult.url;
      console.log(`[Extractor] Image uploaded successfully: ${imageUrl}`);
    } catch (err) {
      console.error('[Extractor] ImageKit upload error:', err);
      // Fallback: If ImageKit fails (500/401), store the image directly as a Base64 data URI
      imageUrl = `data:${file.mimetype};base64,${file.buffer.toString('base64')}`;
      console.log(`[Extractor] Using Base64 fallback for imageUrl.`);
    }
  } else {
    // If imagekit is completely unconfigured, fallback automatically
    imageUrl = `data:${file.mimetype};base64,${file.buffer.toString('base64')}`;
  }

  // Final content will be generated by the consolidated Neural Analysis service
  return {
    title: `Image: ${file.originalname}`,
    content: `Image metadata extraction: Filename: ${file.originalname}, Size: ${file.size} bytes.`,
    metadata: {
      imageUrl,
      imageBuffer: file.buffer.toString('base64'),
      mimeType: file.mimetype
    }
  };
};

export const extractPDF = async (buffer, filename) => {
  if (!buffer) throw new Error('No PDF buffer provided');
  try {
    // pdf-parse v2.4.5 uses PDFParse class in ESM
    const parser = new PDFParse({ data: buffer });
    const result = await parser.getText();
    return {
      title: `PDF: ${filename}`,
      content: result.text
    };
  } catch (error) {
    console.error('PDF Extraction Error:', error);
    throw new Error('Failed to extract text from PDF');
  }
};
